"""Number Guesser Game Implementation generated by Computer

Player needs to guess for a number from 0 to 100 with 5 guesses allowed. The more guesses the player takes the computer will give better hints.
5 total hints:
1) Higher/Lower
2) Higher/Lower
3) Higher/Lower + Less than or Greater than 50
5) Higher/Lower + Tens Digit
4) Higher/Lower + Even/Odd
"""
from random import *

def number_guesser():
    while True:
        print("\nWelcome to Number Guesser\n")
        number = randint(1, 100)
        allowed = 5

        while allowed >= 0:
            try:
                guess = int(input(f"{allowed} guesses to go, guess a number between 1-100: "))
            
                if (type(guess) is not int) or (guess < 1) or (guess > 100):
                    raise ValueError

                if guess == number:
                    print("CORRECT! GREAT GUESS!")
                    break
                elif allowed == 5:
                    if guess < number: print("Higher!")
                    else: print("Lower!")
                elif allowed == 4:
                    if guess < number: print("Higher!")
                    else: print("Lower!")
                elif allowed == 3:
                    if guess < number: print("Higher!")
                    else: print("Lower!")
                    if guess >= 50: print("The number is higher than or equal to 50")
                    else: print("The number is lower than 50")
                elif allowed == 2:
                    if guess < number: print("Higher!")
                    else: print("Lower!")
                    tens = guess // 10 # ceiling division
                    print(f"The tens digit is {tens}, Last 2 guesses!")
                elif allowed == 1:
                    if guess < number: print("Higher!")
                    else: print("Lower!")
                    if number % 2 == 0: print("The number is even")
                    else: print("The number is odd")
                    print("Last Guess Good Luck!")
                allowed -= 1

            except ValueError:
                print("Enter a number between 1 and 100 only!")

        print(f"Good try! The number was {number}")
        play_again = input("Play again? (yes/no): ").lower()
        if play_again != "yes":
            print("Till next time!")
            break

